### PR TITLE
Pytest benchmark tadej

### PR DESCRIPTION
**Pull request by tadejsv**
This is an example of `pytest-benchmark` integration. After installing requirements, run it with
```
pytest --benchmark-save=results.json --benchmark-min-rounds=1
```
And the results will appear in the `.benchmarks` folder (this can all be modified).

Some thoughts:
- Now I agree with @maateen, pytest-benchmark looks really promising. I could cut out all benchmark-specific code I wrote and really only focus on what I wanted to benchmark. Really cool!
- The results are very detailed (maybe too much haha). But they are json, so easy to parse - so we can have a nice separation between "backend" and frontend, as we know what format the outputs will be in.
- Some thought is required so that you write things in a way that you really have all inputs, and just pass them to the function doing the computing.
 Note, for example, that I didn't remove the part that pops embeddings from the `_match_arrays` function. This would be possible if you use the setup function with `benchmark.pendantic`. 
 The only problem with that is that then you have to [specify manually](https://pytest-benchmark.readthedocs.io/en/v3.4.1/pedantic.html#benchmark.pedantic) how many times the function will run (but we were doing this before anyway, so even if we sometimes have to do it, it's still better than before).
 - I guess we should also think a bit about time: pytest-benchmarks have parameters that enable you to control for how much time do you want a benchmark (function) to run, what is the minimum number of times it should be repeated, etc. I think it's useful to think about what we want this to be, taking into account that we may soon have many more functions that we want to benchmark. We just need to agree on something, and then use that.

Overall, I would be in favor of using `pytest-benchmark`. It makes benchmarks easy to write, and is flexible enough that I think we can use it to benchmark everything that we want.

@JoanFM @maateen @bwanglzu , what are your thoughts? Do you prefer this, pure pytest, or something else?

### CODE REVIEW

**Comment by JoanFM** [comment]
Pytest benchmarks seems like a good choice for me

**Comment by JoanFM** [comment]
Does it have also memory profiling?

**Comment by maateen** [comment]
I prefer `pytest-benchmark` over `pytest` if we want time metrics only. But it doesn't provide memory metrics @JoanFM

**Comment by JoanFM** [comment]
Since pytest benchmark seems not to scale with the pontential growth of our needs. Lets discard it.

**Pull request closed without merging**
