### PR TITLE
fix: fix import

### PR DESCRIPTION
**Pull request by JoanFM**

### CODE REVIEW

**Comment by maateen** [comment]
Please check this error:

```python
Traceback (most recent call last):
  File "/Users/maateen/Documents/workspace/jina-ai/benchmark/src/src/document_array_append.py", line 7, in <module>
    from .utils.benchmark import benchmark_time
ImportError: attempted relative import with no known parent package
```

**Comment by JoanFM** [comment]
@tadejsv can u take a look at this?

**Comment by tadejsv** [comment]
@maateen just adding the `src/__init__.py` file like joan did should solve your problem

@JoanFM now imports work, but I am getting error regarding the use of `@pytest.skip`

**Comment by maateen** [comment]
@tadejsv Still, no luck:

```python
➜ python src/document_array_append.py
Traceback (most recent call last):
  File "/Users/maateen/Documents/workspace/jina-ai/benchmark/src/src/document_array_append.py", line 7, in <module>
    from .utils.benchmark import benchmark_time
ImportError: attempted relative import with no known parent package
```

**Comment by maateen** [comment]
FYI,

```shell
➜ ls src/__init__.py
src/__init__.py
```

**Comment by JoanFM** [comment]
@maateen rember you do not do `python src/` but `pytest src/...`

**Comment by maateen** [comment]
Oops! I was running it in the wrong way. The following should do the charm:

```shell
$ pytest
```

**Pull request merged**
